name: loanz
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 
  google_fonts: any
  flutter_svg: 1.0.3
  flutter: 
    sdk: flutter
  pie_chart: ^5.1.0
  syncfusion_flutter_charts: ^19.4.55

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets: 
    - assets/icon/
    - assets/image/

